# Generated by Django 4.0.3 on 2022-03-31 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_glucoselevels_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='col_row',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
